// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// User_Auth is the predicate function for user_auth builders.
type User_Auth func(*sql.Selector)

// User_Profile is the predicate function for user_profile builders.
type User_Profile func(*sql.Selector)
