// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: lib/protos/v1/membership/membership.proto

package membership

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistrationRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Email           string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Fullname        string                 `protobuf:"bytes,2,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Username        string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password        string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	ConfirmPassword string                 `protobuf:"bytes,5,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegistrationRequest) Reset() {
	*x = RegistrationRequest{}
	mi := &file_lib_protos_v1_membership_membership_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationRequest) ProtoMessage() {}

func (x *RegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_protos_v1_membership_membership_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationRequest.ProtoReflect.Descriptor instead.
func (*RegistrationRequest) Descriptor() ([]byte, []int) {
	return file_lib_protos_v1_membership_membership_proto_rawDescGZIP(), []int{0}
}

func (x *RegistrationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegistrationRequest) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *RegistrationRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegistrationRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegistrationRequest) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

type RegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AccountNumber string                 `protobuf:"bytes,2,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationResponse) Reset() {
	*x = RegistrationResponse{}
	mi := &file_lib_protos_v1_membership_membership_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationResponse) ProtoMessage() {}

func (x *RegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_protos_v1_membership_membership_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationResponse.ProtoReflect.Descriptor instead.
func (*RegistrationResponse) Descriptor() ([]byte, []int) {
	return file_lib_protos_v1_membership_membership_proto_rawDescGZIP(), []int{1}
}

func (x *RegistrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegistrationResponse) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *RegistrationResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_lib_protos_v1_membership_membership_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_protos_v1_membership_membership_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_lib_protos_v1_membership_membership_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	LoginMessage  string                 `protobuf:"bytes,2,opt,name=login_message,json=loginMessage,proto3" json:"login_message,omitempty"`
	Uuid          string                 `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_lib_protos_v1_membership_membership_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_protos_v1_membership_membership_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_lib_protos_v1_membership_membership_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoginResponse) GetLoginMessage() string {
	if x != nil {
		return x.LoginMessage
	}
	return ""
}

func (x *LoginResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_lib_protos_v1_membership_membership_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_protos_v1_membership_membership_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_lib_protos_v1_membership_membership_proto_rawDescGZIP(), []int{4}
}

func (x *LogoutRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_lib_protos_v1_membership_membership_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_protos_v1_membership_membership_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_lib_protos_v1_membership_membership_proto_rawDescGZIP(), []int{5}
}

func (x *LogoutResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber string                 `protobuf:"bytes,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoRequest) Reset() {
	*x = UserInfoRequest{}
	mi := &file_lib_protos_v1_membership_membership_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoRequest) ProtoMessage() {}

func (x *UserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_protos_v1_membership_membership_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoRequest.ProtoReflect.Descriptor instead.
func (*UserInfoRequest) Descriptor() ([]byte, []int) {
	return file_lib_protos_v1_membership_membership_proto_rawDescGZIP(), []int{6}
}

func (x *UserInfoRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

type UserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Fullname      string                 `protobuf:"bytes,2,opt,name=fullname,proto3" json:"fullname,omitempty"`
	AccountNumber string                 `protobuf:"bytes,3,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoResponse) Reset() {
	*x = UserInfoResponse{}
	mi := &file_lib_protos_v1_membership_membership_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoResponse) ProtoMessage() {}

func (x *UserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_protos_v1_membership_membership_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoResponse.ProtoReflect.Descriptor instead.
func (*UserInfoResponse) Descriptor() ([]byte, []int) {
	return file_lib_protos_v1_membership_membership_proto_rawDescGZIP(), []int{7}
}

func (x *UserInfoResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfoResponse) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *UserInfoResponse) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *UserInfoResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_lib_protos_v1_membership_membership_proto protoreflect.FileDescriptor

const file_lib_protos_v1_membership_membership_proto_rawDesc = "" +
	"\n" +
	")lib/protos/v1/membership/membership.proto\x12\x1ffastcampus.membership.public.v1\x1a'lib/protos/google/api/annotations.proto\x1a9lib/protos/protoc-gen-openapiv2/options/annotations.proto\"\xaa\x01\n" +
	"\x13RegistrationRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bfullname\x18\x02 \x01(\tR\bfullname\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12)\n" +
	"\x10confirm_password\x18\x05 \x01(\tR\x0fconfirmPassword\"|\n" +
	"\x14RegistrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0eaccount_number\x18\x02 \x01(\tR\raccountNumber\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"b\n" +
	"\rLoginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rlogin_message\x18\x02 \x01(\tR\floginMessage\x12\x12\n" +
	"\x04uuid\x18\x03 \x01(\tR\x04uuid\"#\n" +
	"\rLogoutRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"*\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"8\n" +
	"\x0fUserInfoRequest\x12%\n" +
	"\x0eaccount_number\x18\x01 \x01(\tR\raccountNumber\"\x83\x01\n" +
	"\x10UserInfoResponse\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bfullname\x18\x02 \x01(\tR\bfullname\x12%\n" +
	"\x0eaccount_number\x18\x03 \x01(\tR\raccountNumber\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status2\xd7\x06\n" +
	"\x11MembershipService\x12\xe8\x01\n" +
	"\x12SubmitRegistration\x124.fastcampus.membership.public.v1.RegistrationRequest\x1a5.fastcampus.membership.public.v1.RegistrationResponse\"e\x92A@\n" +
	"\n" +
	"membership\x12\x11Registration User*\x12SubmitRegistrationJ\v\n" +
	"\x03200\x12\x04\n" +
	"\x02OK\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/membership/register\x12\xc8\x01\n" +
	"\fSubmitLogout\x12..fastcampus.membership.public.v1.LogoutRequest\x1a/.fastcampus.membership.public.v1.LogoutResponse\"W\x92A4\n" +
	"\n" +
	"membership\x12\vLogout User*\fSubmitLogoutJ\v\n" +
	"\x03200\x12\x04\n" +
	"\x02OK\x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/membership/logout\x12\xc1\x01\n" +
	"\vSubmitLogin\x12-.fastcampus.membership.public.v1.LoginRequest\x1a..fastcampus.membership.public.v1.LoginResponse\"S\x92A2\n" +
	"\n" +
	"membership\x12\n" +
	"Login User*\vSubmitLoginJ\v\n" +
	"\x03200\x12\x04\n" +
	"\x02OK\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/membership/auth\x12\xc7\x01\n" +
	"\vGetUserInfo\x120.fastcampus.membership.public.v1.UserInfoRequest\x1a1.fastcampus.membership.public.v1.UserInfoResponse\"S\x92A5\n" +
	"\n" +
	"membership\x12\rGet User Info*\vGetUserInfoJ\v\n" +
	"\x03200\x12\x04\n" +
	"\x02OK\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/membership/infoB\xaf\x01\x92AY\x120\n" +
	")Fast Campus Pay (Membership API Endpoint)2\x031.0*\x01\x012\x10application/json:\x10application/jsonZQgithub.com/hasri20/hexagonal-arch-boilerplate/lib/protos/v1/membership;membershipb\x06proto3"

var (
	file_lib_protos_v1_membership_membership_proto_rawDescOnce sync.Once
	file_lib_protos_v1_membership_membership_proto_rawDescData []byte
)

func file_lib_protos_v1_membership_membership_proto_rawDescGZIP() []byte {
	file_lib_protos_v1_membership_membership_proto_rawDescOnce.Do(func() {
		file_lib_protos_v1_membership_membership_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lib_protos_v1_membership_membership_proto_rawDesc), len(file_lib_protos_v1_membership_membership_proto_rawDesc)))
	})
	return file_lib_protos_v1_membership_membership_proto_rawDescData
}

var file_lib_protos_v1_membership_membership_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_lib_protos_v1_membership_membership_proto_goTypes = []any{
	(*RegistrationRequest)(nil),  // 0: fastcampus.membership.public.v1.RegistrationRequest
	(*RegistrationResponse)(nil), // 1: fastcampus.membership.public.v1.RegistrationResponse
	(*LoginRequest)(nil),         // 2: fastcampus.membership.public.v1.LoginRequest
	(*LoginResponse)(nil),        // 3: fastcampus.membership.public.v1.LoginResponse
	(*LogoutRequest)(nil),        // 4: fastcampus.membership.public.v1.LogoutRequest
	(*LogoutResponse)(nil),       // 5: fastcampus.membership.public.v1.LogoutResponse
	(*UserInfoRequest)(nil),      // 6: fastcampus.membership.public.v1.UserInfoRequest
	(*UserInfoResponse)(nil),     // 7: fastcampus.membership.public.v1.UserInfoResponse
}
var file_lib_protos_v1_membership_membership_proto_depIdxs = []int32{
	0, // 0: fastcampus.membership.public.v1.MembershipService.SubmitRegistration:input_type -> fastcampus.membership.public.v1.RegistrationRequest
	4, // 1: fastcampus.membership.public.v1.MembershipService.SubmitLogout:input_type -> fastcampus.membership.public.v1.LogoutRequest
	2, // 2: fastcampus.membership.public.v1.MembershipService.SubmitLogin:input_type -> fastcampus.membership.public.v1.LoginRequest
	6, // 3: fastcampus.membership.public.v1.MembershipService.GetUserInfo:input_type -> fastcampus.membership.public.v1.UserInfoRequest
	1, // 4: fastcampus.membership.public.v1.MembershipService.SubmitRegistration:output_type -> fastcampus.membership.public.v1.RegistrationResponse
	5, // 5: fastcampus.membership.public.v1.MembershipService.SubmitLogout:output_type -> fastcampus.membership.public.v1.LogoutResponse
	3, // 6: fastcampus.membership.public.v1.MembershipService.SubmitLogin:output_type -> fastcampus.membership.public.v1.LoginResponse
	7, // 7: fastcampus.membership.public.v1.MembershipService.GetUserInfo:output_type -> fastcampus.membership.public.v1.UserInfoResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lib_protos_v1_membership_membership_proto_init() }
func file_lib_protos_v1_membership_membership_proto_init() {
	if File_lib_protos_v1_membership_membership_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lib_protos_v1_membership_membership_proto_rawDesc), len(file_lib_protos_v1_membership_membership_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lib_protos_v1_membership_membership_proto_goTypes,
		DependencyIndexes: file_lib_protos_v1_membership_membership_proto_depIdxs,
		MessageInfos:      file_lib_protos_v1_membership_membership_proto_msgTypes,
	}.Build()
	File_lib_protos_v1_membership_membership_proto = out.File
	file_lib_protos_v1_membership_membership_proto_goTypes = nil
	file_lib_protos_v1_membership_membership_proto_depIdxs = nil
}
