// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: lib/protos/v1/payment/payment.proto

package payment

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceUserId  string                 `protobuf:"bytes,1,opt,name=source_user_id,json=sourceUserId,proto3" json:"source_user_id,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferBalanceRequest) Reset() {
	*x = TransferBalanceRequest{}
	mi := &file_lib_protos_v1_payment_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferBalanceRequest) ProtoMessage() {}

func (x *TransferBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_protos_v1_payment_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferBalanceRequest.ProtoReflect.Descriptor instead.
func (*TransferBalanceRequest) Descriptor() ([]byte, []int) {
	return file_lib_protos_v1_payment_payment_proto_rawDescGZIP(), []int{0}
}

func (x *TransferBalanceRequest) GetSourceUserId() string {
	if x != nil {
		return x.SourceUserId
	}
	return ""
}

func (x *TransferBalanceRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *TransferBalanceRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type TransferBalanceResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	DestinationAmount float64                `protobuf:"fixed64,2,opt,name=destination_amount,json=destinationAmount,proto3" json:"destination_amount,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TransferBalanceResponse) Reset() {
	*x = TransferBalanceResponse{}
	mi := &file_lib_protos_v1_payment_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferBalanceResponse) ProtoMessage() {}

func (x *TransferBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_protos_v1_payment_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferBalanceResponse.ProtoReflect.Descriptor instead.
func (*TransferBalanceResponse) Descriptor() ([]byte, []int) {
	return file_lib_protos_v1_payment_payment_proto_rawDescGZIP(), []int{1}
}

func (x *TransferBalanceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TransferBalanceResponse) GetDestinationAmount() float64 {
	if x != nil {
		return x.DestinationAmount
	}
	return 0
}

var File_lib_protos_v1_payment_payment_proto protoreflect.FileDescriptor

const file_lib_protos_v1_payment_payment_proto_rawDesc = "" +
	"\n" +
	"#lib/protos/v1/payment/payment.proto\x12\x1cfastcampus.payment.public.v1\x1a'lib/protos/google/api/annotations.proto\x1a9lib/protos/protoc-gen-openapiv2/options/annotations.proto\"x\n" +
	"\x16TransferBalanceRequest\x12$\n" +
	"\x0esource_user_id\x18\x01 \x01(\tR\fsourceUserId\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\"b\n" +
	"\x17TransferBalanceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12-\n" +
	"\x12destination_amount\x18\x02 \x01(\x01R\x11destinationAmount2\x89\x02\n" +
	"\x0ePaymentService\x12\xf6\x01\n" +
	"\x16TransferBalanceService\x124.fastcampus.payment.public.v1.TransferBalanceRequest\x1a5.fastcampus.payment.public.v1.TransferBalanceResponse\"o\x92AM\n" +
	"\apayment\x12\x1dTransfer Users Balance Amount*\x16TransferBalanceServiceJ\v\n" +
	"\x03200\x12\x04\n" +
	"\x02OK\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/payment/transferB\xfc\x01\x92A\xa3\x01\x12z\n" +
	"&Fast Campus Pay (Payment API Endpoint)\"K\n" +
	"\x13Fast Campus Payment\x12\x1ehttps://github.com/titikterang\x1a\x14azwar.nrst@gmail.com2\x031.0*\x01\x012\x10application/json:\x10application/jsonZSgithub.com/titikterang/hexagonal-arch-boilerplate/lib/protos/public/payment;paymentb\x06proto3"

var (
	file_lib_protos_v1_payment_payment_proto_rawDescOnce sync.Once
	file_lib_protos_v1_payment_payment_proto_rawDescData []byte
)

func file_lib_protos_v1_payment_payment_proto_rawDescGZIP() []byte {
	file_lib_protos_v1_payment_payment_proto_rawDescOnce.Do(func() {
		file_lib_protos_v1_payment_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lib_protos_v1_payment_payment_proto_rawDesc), len(file_lib_protos_v1_payment_payment_proto_rawDesc)))
	})
	return file_lib_protos_v1_payment_payment_proto_rawDescData
}

var file_lib_protos_v1_payment_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_lib_protos_v1_payment_payment_proto_goTypes = []any{
	(*TransferBalanceRequest)(nil),  // 0: fastcampus.payment.public.v1.TransferBalanceRequest
	(*TransferBalanceResponse)(nil), // 1: fastcampus.payment.public.v1.TransferBalanceResponse
}
var file_lib_protos_v1_payment_payment_proto_depIdxs = []int32{
	0, // 0: fastcampus.payment.public.v1.PaymentService.TransferBalanceService:input_type -> fastcampus.payment.public.v1.TransferBalanceRequest
	1, // 1: fastcampus.payment.public.v1.PaymentService.TransferBalanceService:output_type -> fastcampus.payment.public.v1.TransferBalanceResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lib_protos_v1_payment_payment_proto_init() }
func file_lib_protos_v1_payment_payment_proto_init() {
	if File_lib_protos_v1_payment_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lib_protos_v1_payment_payment_proto_rawDesc), len(file_lib_protos_v1_payment_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lib_protos_v1_payment_payment_proto_goTypes,
		DependencyIndexes: file_lib_protos_v1_payment_payment_proto_depIdxs,
		MessageInfos:      file_lib_protos_v1_payment_payment_proto_msgTypes,
	}.Build()
	File_lib_protos_v1_payment_payment_proto = out.File
	file_lib_protos_v1_payment_payment_proto_goTypes = nil
	file_lib_protos_v1_payment_payment_proto_depIdxs = nil
}
