// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: lib/protos/google/api/annotations.proto

package annotations

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_lib_protos_google_api_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*HttpRule)(nil),
		Field:         72295728,
		Name:          "google.api.http",
		Tag:           "bytes,72295728,opt,name=http",
		Filename:      "lib/protos/google/api/annotations.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// See `HttpRule`.
	//
	// optional google.api.HttpRule http = 72295728;
	E_Http = &file_lib_protos_google_api_annotations_proto_extTypes[0]
)

var File_lib_protos_google_api_annotations_proto protoreflect.FileDescriptor

const file_lib_protos_google_api_annotations_proto_rawDesc = "" +
	"\n" +
	"'lib/protos/google/api/annotations.proto\x12\n" +
	"google.api\x1a lib/protos/google/api/http.proto\x1a google/protobuf/descriptor.proto:K\n" +
	"\x04http\x12\x1e.google.protobuf.MethodOptions\x18\xb0ʼ\" \x01(\v2\x14.google.api.HttpRuleR\x04httpBn\n" +
	"\x0ecom.google.apiB\x10AnnotationsProtoP\x01ZAgoogle.golang.org/genproto/googleapis/api/annotations;annotations\xa2\x02\x04GAPIb\x06proto3"

var file_lib_protos_google_api_annotations_proto_goTypes = []any{
	(*descriptorpb.MethodOptions)(nil), // 0: google.protobuf.MethodOptions
	(*HttpRule)(nil),                   // 1: google.api.HttpRule
}
var file_lib_protos_google_api_annotations_proto_depIdxs = []int32{
	0, // 0: google.api.http:extendee -> google.protobuf.MethodOptions
	1, // 1: google.api.http:type_name -> google.api.HttpRule
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lib_protos_google_api_annotations_proto_init() }
func file_lib_protos_google_api_annotations_proto_init() {
	if File_lib_protos_google_api_annotations_proto != nil {
		return
	}
	file_lib_protos_google_api_http_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lib_protos_google_api_annotations_proto_rawDesc), len(file_lib_protos_google_api_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_lib_protos_google_api_annotations_proto_goTypes,
		DependencyIndexes: file_lib_protos_google_api_annotations_proto_depIdxs,
		ExtensionInfos:    file_lib_protos_google_api_annotations_proto_extTypes,
	}.Build()
	File_lib_protos_google_api_annotations_proto = out.File
	file_lib_protos_google_api_annotations_proto_goTypes = nil
	file_lib_protos_google_api_annotations_proto_depIdxs = nil
}
