-- Create "user_auths" table
CREATE TABLE "user_auths" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "account_number" character varying NOT NULL,
  "username" character varying NOT NULL,
  "hash" character varying NOT NULL,
  "last_login" timestamptz NOT NULL,
  "created_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "user_auths_account_number_key" to table: "user_auths"
CREATE UNIQUE INDEX "user_auths_account_number_key" ON "user_auths" ("account_number");
-- Create "user_profiles" table
CREATE TABLE "user_profiles" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "account_number" character varying NOT NULL,
  "fullname" character varying NOT NULL,
  "status" character varying NOT NULL,
  "email" character varying NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "user_profiles_account_number_key" to table: "user_profiles"
CREATE UNIQUE INDEX "user_profiles_account_number_key" ON "user_profiles" ("account_number");
