// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: lib/protos/v1/wallet/wallet.proto

package wallet

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBalanceRequest) Reset() {
	*x = UpdateBalanceRequest{}
	mi := &file_lib_protos_v1_wallet_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBalanceRequest) ProtoMessage() {}

func (x *UpdateBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_protos_v1_wallet_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBalanceRequest.ProtoReflect.Descriptor instead.
func (*UpdateBalanceRequest) Descriptor() ([]byte, []int) {
	return file_lib_protos_v1_wallet_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateBalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateBalanceRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type UpdateBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	FinalBalance  float64                `protobuf:"fixed64,3,opt,name=final_balance,json=finalBalance,proto3" json:"final_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBalanceResponse) Reset() {
	*x = UpdateBalanceResponse{}
	mi := &file_lib_protos_v1_wallet_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBalanceResponse) ProtoMessage() {}

func (x *UpdateBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_protos_v1_wallet_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBalanceResponse.ProtoReflect.Descriptor instead.
func (*UpdateBalanceResponse) Descriptor() ([]byte, []int) {
	return file_lib_protos_v1_wallet_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateBalanceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateBalanceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateBalanceResponse) GetFinalBalance() float64 {
	if x != nil {
		return x.FinalBalance
	}
	return 0
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_lib_protos_v1_wallet_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lib_protos_v1_wallet_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_lib_protos_v1_wallet_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *GetBalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Balance       float64                `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_lib_protos_v1_wallet_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lib_protos_v1_wallet_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_lib_protos_v1_wallet_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *GetBalanceResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetBalanceResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

var File_lib_protos_v1_wallet_wallet_proto protoreflect.FileDescriptor

const file_lib_protos_v1_wallet_wallet_proto_rawDesc = "" +
	"\n" +
	"!lib/protos/v1/wallet/wallet.proto\x12\x1bfastcampus.wallet.public.v1\x1a'lib/protos/google/api/annotations.proto\x1a9lib/protos/protoc-gen-openapiv2/options/annotations.proto\"G\n" +
	"\x14UpdateBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\"p\n" +
	"\x15UpdateBalanceResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rfinal_balance\x18\x03 \x01(\x01R\ffinalBalance\",\n" +
	"\x11GetBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"G\n" +
	"\x12GetBalanceResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x01R\abalance2\xc2\x03\n" +
	"\rWalletService\x12\xce\x01\n" +
	"\x0eGetUserBalance\x12..fastcampus.wallet.public.v1.GetBalanceRequest\x1a/.fastcampus.wallet.public.v1.GetBalanceResponse\"[\x92A>\n" +
	"\abalance\x12\x16Get Users Balance Info*\x0eGetUserBalanceJ\v\n" +
	"\x03200\x12\x04\n" +
	"\x02OK\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/wallet/balance\x12\xdf\x01\n" +
	"\x11UpdateUserBalance\x121.fastcampus.wallet.public.v1.UpdateBalanceRequest\x1a2.fastcampus.wallet.public.v1.UpdateBalanceResponse\"c\x92AD\n" +
	"\abalance\x12\x19Update Users Balance Info*\x11UpdateUserBalanceJ\v\n" +
	"\x03200\x12\x04\n" +
	"\x02OK\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/wallet/updateB\xf5\x01\x92A\xa2\x01\x12y\n" +
	"%Fast Campus Pay (Wallet API Endpoint)\"K\n" +
	"\x13Fast Campus Payment\x12\x1ehttps://github.com/titikterang\x1a\x14azwar.nrst@gmail.com2\x031.0*\x01\x012\x10application/json:\x10application/jsonZMgithub.com/hasri20/hexagonal-arch-boilerplate/lib/protos/public/wallet;walletb\x06proto3"

var (
	file_lib_protos_v1_wallet_wallet_proto_rawDescOnce sync.Once
	file_lib_protos_v1_wallet_wallet_proto_rawDescData []byte
)

func file_lib_protos_v1_wallet_wallet_proto_rawDescGZIP() []byte {
	file_lib_protos_v1_wallet_wallet_proto_rawDescOnce.Do(func() {
		file_lib_protos_v1_wallet_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lib_protos_v1_wallet_wallet_proto_rawDesc), len(file_lib_protos_v1_wallet_wallet_proto_rawDesc)))
	})
	return file_lib_protos_v1_wallet_wallet_proto_rawDescData
}

var file_lib_protos_v1_wallet_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_lib_protos_v1_wallet_wallet_proto_goTypes = []any{
	(*UpdateBalanceRequest)(nil),  // 0: fastcampus.wallet.public.v1.UpdateBalanceRequest
	(*UpdateBalanceResponse)(nil), // 1: fastcampus.wallet.public.v1.UpdateBalanceResponse
	(*GetBalanceRequest)(nil),     // 2: fastcampus.wallet.public.v1.GetBalanceRequest
	(*GetBalanceResponse)(nil),    // 3: fastcampus.wallet.public.v1.GetBalanceResponse
}
var file_lib_protos_v1_wallet_wallet_proto_depIdxs = []int32{
	2, // 0: fastcampus.wallet.public.v1.WalletService.GetUserBalance:input_type -> fastcampus.wallet.public.v1.GetBalanceRequest
	0, // 1: fastcampus.wallet.public.v1.WalletService.UpdateUserBalance:input_type -> fastcampus.wallet.public.v1.UpdateBalanceRequest
	3, // 2: fastcampus.wallet.public.v1.WalletService.GetUserBalance:output_type -> fastcampus.wallet.public.v1.GetBalanceResponse
	1, // 3: fastcampus.wallet.public.v1.WalletService.UpdateUserBalance:output_type -> fastcampus.wallet.public.v1.UpdateBalanceResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lib_protos_v1_wallet_wallet_proto_init() }
func file_lib_protos_v1_wallet_wallet_proto_init() {
	if File_lib_protos_v1_wallet_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lib_protos_v1_wallet_wallet_proto_rawDesc), len(file_lib_protos_v1_wallet_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lib_protos_v1_wallet_wallet_proto_goTypes,
		DependencyIndexes: file_lib_protos_v1_wallet_wallet_proto_depIdxs,
		MessageInfos:      file_lib_protos_v1_wallet_wallet_proto_msgTypes,
	}.Build()
	File_lib_protos_v1_wallet_wallet_proto = out.File
	file_lib_protos_v1_wallet_wallet_proto_goTypes = nil
	file_lib_protos_v1_wallet_wallet_proto_depIdxs = nil
}
