// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/hasri20/hexagonal-arch-boilerplate/internal/membership/ent/schema"
	"github.com/hasri20/hexagonal-arch-boilerplate/internal/membership/ent/user_auth"
	"github.com/hasri20/hexagonal-arch-boilerplate/internal/membership/ent/user_profile"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	user_authFields := schema.User_Auth{}.Fields()
	_ = user_authFields
	// user_authDescAccountNumber is the schema descriptor for account_number field.
	user_authDescAccountNumber := user_authFields[0].Descriptor()
	// user_auth.AccountNumberValidator is a validator for the "account_number" field. It is called by the builders before save.
	user_auth.AccountNumberValidator = user_authDescAccountNumber.Validators[0].(func(string) error)
	// user_authDescUsername is the schema descriptor for username field.
	user_authDescUsername := user_authFields[1].Descriptor()
	// user_auth.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user_auth.UsernameValidator = func() func(string) error {
		validators := user_authDescUsername.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(username string) error {
			for _, fn := range fns {
				if err := fn(username); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// user_authDescHash is the schema descriptor for hash field.
	user_authDescHash := user_authFields[2].Descriptor()
	// user_auth.HashValidator is a validator for the "hash" field. It is called by the builders before save.
	user_auth.HashValidator = func() func(string) error {
		validators := user_authDescHash.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(hash string) error {
			for _, fn := range fns {
				if err := fn(hash); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// user_authDescCreatedAt is the schema descriptor for created_at field.
	user_authDescCreatedAt := user_authFields[4].Descriptor()
	// user_auth.DefaultCreatedAt holds the default value on creation for the created_at field.
	user_auth.DefaultCreatedAt = user_authDescCreatedAt.Default.(func() time.Time)
	user_profileFields := schema.User_Profile{}.Fields()
	_ = user_profileFields
	// user_profileDescAccountNumber is the schema descriptor for account_number field.
	user_profileDescAccountNumber := user_profileFields[0].Descriptor()
	// user_profile.AccountNumberValidator is a validator for the "account_number" field. It is called by the builders before save.
	user_profile.AccountNumberValidator = user_profileDescAccountNumber.Validators[0].(func(string) error)
	// user_profileDescFullname is the schema descriptor for fullname field.
	user_profileDescFullname := user_profileFields[1].Descriptor()
	// user_profile.FullnameValidator is a validator for the "fullname" field. It is called by the builders before save.
	user_profile.FullnameValidator = func() func(string) error {
		validators := user_profileDescFullname.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(fullname string) error {
			for _, fn := range fns {
				if err := fn(fullname); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// user_profileDescStatus is the schema descriptor for status field.
	user_profileDescStatus := user_profileFields[2].Descriptor()
	// user_profile.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	user_profile.StatusValidator = func() func(string) error {
		validators := user_profileDescStatus.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(status string) error {
			for _, fn := range fns {
				if err := fn(status); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// user_profileDescEmail is the schema descriptor for email field.
	user_profileDescEmail := user_profileFields[3].Descriptor()
	// user_profile.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user_profile.EmailValidator = func() func(string) error {
		validators := user_profileDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// user_profileDescCreatedAt is the schema descriptor for created_at field.
	user_profileDescCreatedAt := user_profileFields[4].Descriptor()
	// user_profile.DefaultCreatedAt holds the default value on creation for the created_at field.
	user_profile.DefaultCreatedAt = user_profileDescCreatedAt.Default.(func() time.Time)
	// user_profileDescUpdatedAt is the schema descriptor for updated_at field.
	user_profileDescUpdatedAt := user_profileFields[5].Descriptor()
	// user_profile.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user_profile.DefaultUpdatedAt = user_profileDescUpdatedAt.Default.(func() time.Time)
	// user_profile.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user_profile.UpdateDefaultUpdatedAt = user_profileDescUpdatedAt.UpdateDefault.(func() time.Time)
}
