// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hasri20/hexagonal-arch-boilerplate/internal/membership/ent/predicate"
	"github.com/hasri20/hexagonal-arch-boilerplate/internal/membership/ent/user_auth"
)

// UserAuthUpdate is the builder for updating User_Auth entities.
type UserAuthUpdate struct {
	config
	hooks    []Hook
	mutation *UserAuthMutation
}

// Where appends a list predicates to the UserAuthUpdate builder.
func (_u *UserAuthUpdate) Where(ps ...predicate.User_Auth) *UserAuthUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccountNumber sets the "account_number" field.
func (_u *UserAuthUpdate) SetAccountNumber(v string) *UserAuthUpdate {
	_u.mutation.SetAccountNumber(v)
	return _u
}

// SetNillableAccountNumber sets the "account_number" field if the given value is not nil.
func (_u *UserAuthUpdate) SetNillableAccountNumber(v *string) *UserAuthUpdate {
	if v != nil {
		_u.SetAccountNumber(*v)
	}
	return _u
}

// SetUsername sets the "username" field.
func (_u *UserAuthUpdate) SetUsername(v string) *UserAuthUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *UserAuthUpdate) SetNillableUsername(v *string) *UserAuthUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetHash sets the "hash" field.
func (_u *UserAuthUpdate) SetHash(v string) *UserAuthUpdate {
	_u.mutation.SetHash(v)
	return _u
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_u *UserAuthUpdate) SetNillableHash(v *string) *UserAuthUpdate {
	if v != nil {
		_u.SetHash(*v)
	}
	return _u
}

// SetLastLogin sets the "last_login" field.
func (_u *UserAuthUpdate) SetLastLogin(v time.Time) *UserAuthUpdate {
	_u.mutation.SetLastLogin(v)
	return _u
}

// SetNillableLastLogin sets the "last_login" field if the given value is not nil.
func (_u *UserAuthUpdate) SetNillableLastLogin(v *time.Time) *UserAuthUpdate {
	if v != nil {
		_u.SetLastLogin(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UserAuthUpdate) SetCreatedAt(v time.Time) *UserAuthUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UserAuthUpdate) SetNillableCreatedAt(v *time.Time) *UserAuthUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the UserAuthMutation object of the builder.
func (_u *UserAuthUpdate) Mutation() *UserAuthMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserAuthUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserAuthUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserAuthUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserAuthUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserAuthUpdate) check() error {
	if v, ok := _u.mutation.AccountNumber(); ok {
		if err := user_auth.AccountNumberValidator(v); err != nil {
			return &ValidationError{Name: "account_number", err: fmt.Errorf(`ent: validator failed for field "User_Auth.account_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Username(); ok {
		if err := user_auth.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "User_Auth.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Hash(); ok {
		if err := user_auth.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "User_Auth.hash": %w`, err)}
		}
	}
	return nil
}

func (_u *UserAuthUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user_auth.Table, user_auth.Columns, sqlgraph.NewFieldSpec(user_auth.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccountNumber(); ok {
		_spec.SetField(user_auth.FieldAccountNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(user_auth.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(user_auth.FieldHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastLogin(); ok {
		_spec.SetField(user_auth.FieldLastLogin, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(user_auth.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user_auth.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserAuthUpdateOne is the builder for updating a single User_Auth entity.
type UserAuthUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserAuthMutation
}

// SetAccountNumber sets the "account_number" field.
func (_u *UserAuthUpdateOne) SetAccountNumber(v string) *UserAuthUpdateOne {
	_u.mutation.SetAccountNumber(v)
	return _u
}

// SetNillableAccountNumber sets the "account_number" field if the given value is not nil.
func (_u *UserAuthUpdateOne) SetNillableAccountNumber(v *string) *UserAuthUpdateOne {
	if v != nil {
		_u.SetAccountNumber(*v)
	}
	return _u
}

// SetUsername sets the "username" field.
func (_u *UserAuthUpdateOne) SetUsername(v string) *UserAuthUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *UserAuthUpdateOne) SetNillableUsername(v *string) *UserAuthUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetHash sets the "hash" field.
func (_u *UserAuthUpdateOne) SetHash(v string) *UserAuthUpdateOne {
	_u.mutation.SetHash(v)
	return _u
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_u *UserAuthUpdateOne) SetNillableHash(v *string) *UserAuthUpdateOne {
	if v != nil {
		_u.SetHash(*v)
	}
	return _u
}

// SetLastLogin sets the "last_login" field.
func (_u *UserAuthUpdateOne) SetLastLogin(v time.Time) *UserAuthUpdateOne {
	_u.mutation.SetLastLogin(v)
	return _u
}

// SetNillableLastLogin sets the "last_login" field if the given value is not nil.
func (_u *UserAuthUpdateOne) SetNillableLastLogin(v *time.Time) *UserAuthUpdateOne {
	if v != nil {
		_u.SetLastLogin(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UserAuthUpdateOne) SetCreatedAt(v time.Time) *UserAuthUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UserAuthUpdateOne) SetNillableCreatedAt(v *time.Time) *UserAuthUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the UserAuthMutation object of the builder.
func (_u *UserAuthUpdateOne) Mutation() *UserAuthMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserAuthUpdate builder.
func (_u *UserAuthUpdateOne) Where(ps ...predicate.User_Auth) *UserAuthUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserAuthUpdateOne) Select(field string, fields ...string) *UserAuthUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User_Auth entity.
func (_u *UserAuthUpdateOne) Save(ctx context.Context) (*User_Auth, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserAuthUpdateOne) SaveX(ctx context.Context) *User_Auth {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserAuthUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserAuthUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserAuthUpdateOne) check() error {
	if v, ok := _u.mutation.AccountNumber(); ok {
		if err := user_auth.AccountNumberValidator(v); err != nil {
			return &ValidationError{Name: "account_number", err: fmt.Errorf(`ent: validator failed for field "User_Auth.account_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Username(); ok {
		if err := user_auth.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "User_Auth.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Hash(); ok {
		if err := user_auth.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "User_Auth.hash": %w`, err)}
		}
	}
	return nil
}

func (_u *UserAuthUpdateOne) sqlSave(ctx context.Context) (_node *User_Auth, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user_auth.Table, user_auth.Columns, sqlgraph.NewFieldSpec(user_auth.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User_Auth.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user_auth.FieldID)
		for _, f := range fields {
			if !user_auth.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user_auth.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccountNumber(); ok {
		_spec.SetField(user_auth.FieldAccountNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(user_auth.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(user_auth.FieldHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastLogin(); ok {
		_spec.SetField(user_auth.FieldLastLogin, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(user_auth.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &User_Auth{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user_auth.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
