// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hasri20/hexagonal-arch-boilerplate/internal/membership/ent/user_auth"
)

// UserAuthCreate is the builder for creating a User_Auth entity.
type UserAuthCreate struct {
	config
	mutation *UserAuthMutation
	hooks    []Hook
}

// SetAccountNumber sets the "account_number" field.
func (_c *UserAuthCreate) SetAccountNumber(v string) *UserAuthCreate {
	_c.mutation.SetAccountNumber(v)
	return _c
}

// SetUsername sets the "username" field.
func (_c *UserAuthCreate) SetUsername(v string) *UserAuthCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetHash sets the "hash" field.
func (_c *UserAuthCreate) SetHash(v string) *UserAuthCreate {
	_c.mutation.SetHash(v)
	return _c
}

// SetLastLogin sets the "last_login" field.
func (_c *UserAuthCreate) SetLastLogin(v time.Time) *UserAuthCreate {
	_c.mutation.SetLastLogin(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserAuthCreate) SetCreatedAt(v time.Time) *UserAuthCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserAuthCreate) SetNillableCreatedAt(v *time.Time) *UserAuthCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the UserAuthMutation object of the builder.
func (_c *UserAuthCreate) Mutation() *UserAuthMutation {
	return _c.mutation
}

// Save creates the User_Auth in the database.
func (_c *UserAuthCreate) Save(ctx context.Context) (*User_Auth, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserAuthCreate) SaveX(ctx context.Context) *User_Auth {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserAuthCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserAuthCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserAuthCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := user_auth.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserAuthCreate) check() error {
	if _, ok := _c.mutation.AccountNumber(); !ok {
		return &ValidationError{Name: "account_number", err: errors.New(`ent: missing required field "User_Auth.account_number"`)}
	}
	if v, ok := _c.mutation.AccountNumber(); ok {
		if err := user_auth.AccountNumberValidator(v); err != nil {
			return &ValidationError{Name: "account_number", err: fmt.Errorf(`ent: validator failed for field "User_Auth.account_number": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "User_Auth.username"`)}
	}
	if v, ok := _c.mutation.Username(); ok {
		if err := user_auth.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "User_Auth.username": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Hash(); !ok {
		return &ValidationError{Name: "hash", err: errors.New(`ent: missing required field "User_Auth.hash"`)}
	}
	if v, ok := _c.mutation.Hash(); ok {
		if err := user_auth.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "User_Auth.hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastLogin(); !ok {
		return &ValidationError{Name: "last_login", err: errors.New(`ent: missing required field "User_Auth.last_login"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "User_Auth.created_at"`)}
	}
	return nil
}

func (_c *UserAuthCreate) sqlSave(ctx context.Context) (*User_Auth, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserAuthCreate) createSpec() (*User_Auth, *sqlgraph.CreateSpec) {
	var (
		_node = &User_Auth{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(user_auth.Table, sqlgraph.NewFieldSpec(user_auth.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.AccountNumber(); ok {
		_spec.SetField(user_auth.FieldAccountNumber, field.TypeString, value)
		_node.AccountNumber = value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(user_auth.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.Hash(); ok {
		_spec.SetField(user_auth.FieldHash, field.TypeString, value)
		_node.Hash = value
	}
	if value, ok := _c.mutation.LastLogin(); ok {
		_spec.SetField(user_auth.FieldLastLogin, field.TypeTime, value)
		_node.LastLogin = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(user_auth.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// UserAuthCreateBulk is the builder for creating many User_Auth entities in bulk.
type UserAuthCreateBulk struct {
	config
	err      error
	builders []*UserAuthCreate
}

// Save creates the User_Auth entities in the database.
func (_c *UserAuthCreateBulk) Save(ctx context.Context) ([]*User_Auth, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*User_Auth, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserAuthMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserAuthCreateBulk) SaveX(ctx context.Context) []*User_Auth {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserAuthCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserAuthCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
