// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hasri20/hexagonal-arch-boilerplate/internal/membership/ent/user_profile"
)

// UserProfileCreate is the builder for creating a User_Profile entity.
type UserProfileCreate struct {
	config
	mutation *UserProfileMutation
	hooks    []Hook
}

// SetAccountNumber sets the "account_number" field.
func (_c *UserProfileCreate) SetAccountNumber(v string) *UserProfileCreate {
	_c.mutation.SetAccountNumber(v)
	return _c
}

// SetFullname sets the "fullname" field.
func (_c *UserProfileCreate) SetFullname(v string) *UserProfileCreate {
	_c.mutation.SetFullname(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *UserProfileCreate) SetStatus(v string) *UserProfileCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *UserProfileCreate) SetEmail(v string) *UserProfileCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserProfileCreate) SetCreatedAt(v time.Time) *UserProfileCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserProfileCreate) SetNillableCreatedAt(v *time.Time) *UserProfileCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserProfileCreate) SetUpdatedAt(v time.Time) *UserProfileCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserProfileCreate) SetNillableUpdatedAt(v *time.Time) *UserProfileCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the UserProfileMutation object of the builder.
func (_c *UserProfileCreate) Mutation() *UserProfileMutation {
	return _c.mutation
}

// Save creates the User_Profile in the database.
func (_c *UserProfileCreate) Save(ctx context.Context) (*User_Profile, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserProfileCreate) SaveX(ctx context.Context) *User_Profile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserProfileCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserProfileCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserProfileCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := user_profile.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := user_profile.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserProfileCreate) check() error {
	if _, ok := _c.mutation.AccountNumber(); !ok {
		return &ValidationError{Name: "account_number", err: errors.New(`ent: missing required field "User_Profile.account_number"`)}
	}
	if v, ok := _c.mutation.AccountNumber(); ok {
		if err := user_profile.AccountNumberValidator(v); err != nil {
			return &ValidationError{Name: "account_number", err: fmt.Errorf(`ent: validator failed for field "User_Profile.account_number": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Fullname(); !ok {
		return &ValidationError{Name: "fullname", err: errors.New(`ent: missing required field "User_Profile.fullname"`)}
	}
	if v, ok := _c.mutation.Fullname(); ok {
		if err := user_profile.FullnameValidator(v); err != nil {
			return &ValidationError{Name: "fullname", err: fmt.Errorf(`ent: validator failed for field "User_Profile.fullname": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "User_Profile.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := user_profile.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "User_Profile.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "User_Profile.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := user_profile.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User_Profile.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "User_Profile.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "User_Profile.updated_at"`)}
	}
	return nil
}

func (_c *UserProfileCreate) sqlSave(ctx context.Context) (*User_Profile, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserProfileCreate) createSpec() (*User_Profile, *sqlgraph.CreateSpec) {
	var (
		_node = &User_Profile{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(user_profile.Table, sqlgraph.NewFieldSpec(user_profile.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.AccountNumber(); ok {
		_spec.SetField(user_profile.FieldAccountNumber, field.TypeString, value)
		_node.AccountNumber = value
	}
	if value, ok := _c.mutation.Fullname(); ok {
		_spec.SetField(user_profile.FieldFullname, field.TypeString, value)
		_node.Fullname = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(user_profile.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(user_profile.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(user_profile.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(user_profile.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// UserProfileCreateBulk is the builder for creating many User_Profile entities in bulk.
type UserProfileCreateBulk struct {
	config
	err      error
	builders []*UserProfileCreate
}

// Save creates the User_Profile entities in the database.
func (_c *UserProfileCreateBulk) Save(ctx context.Context) ([]*User_Profile, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*User_Profile, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserProfileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserProfileCreateBulk) SaveX(ctx context.Context) []*User_Profile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserProfileCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserProfileCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
