// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/hasri20/hexagonal-arch-boilerplate/internal/membership/ent/predicate"
	"github.com/hasri20/hexagonal-arch-boilerplate/internal/membership/ent/user_profile"
)

// UserProfileUpdate is the builder for updating User_Profile entities.
type UserProfileUpdate struct {
	config
	hooks    []Hook
	mutation *UserProfileMutation
}

// Where appends a list predicates to the UserProfileUpdate builder.
func (_u *UserProfileUpdate) Where(ps ...predicate.User_Profile) *UserProfileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccountNumber sets the "account_number" field.
func (_u *UserProfileUpdate) SetAccountNumber(v string) *UserProfileUpdate {
	_u.mutation.SetAccountNumber(v)
	return _u
}

// SetNillableAccountNumber sets the "account_number" field if the given value is not nil.
func (_u *UserProfileUpdate) SetNillableAccountNumber(v *string) *UserProfileUpdate {
	if v != nil {
		_u.SetAccountNumber(*v)
	}
	return _u
}

// SetFullname sets the "fullname" field.
func (_u *UserProfileUpdate) SetFullname(v string) *UserProfileUpdate {
	_u.mutation.SetFullname(v)
	return _u
}

// SetNillableFullname sets the "fullname" field if the given value is not nil.
func (_u *UserProfileUpdate) SetNillableFullname(v *string) *UserProfileUpdate {
	if v != nil {
		_u.SetFullname(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserProfileUpdate) SetStatus(v string) *UserProfileUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserProfileUpdate) SetNillableStatus(v *string) *UserProfileUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserProfileUpdate) SetEmail(v string) *UserProfileUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserProfileUpdate) SetNillableEmail(v *string) *UserProfileUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UserProfileUpdate) SetCreatedAt(v time.Time) *UserProfileUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UserProfileUpdate) SetNillableCreatedAt(v *time.Time) *UserProfileUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserProfileUpdate) SetUpdatedAt(v time.Time) *UserProfileUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UserProfileMutation object of the builder.
func (_u *UserProfileUpdate) Mutation() *UserProfileMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserProfileUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserProfileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserProfileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserProfileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserProfileUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user_profile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserProfileUpdate) check() error {
	if v, ok := _u.mutation.AccountNumber(); ok {
		if err := user_profile.AccountNumberValidator(v); err != nil {
			return &ValidationError{Name: "account_number", err: fmt.Errorf(`ent: validator failed for field "User_Profile.account_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Fullname(); ok {
		if err := user_profile.FullnameValidator(v); err != nil {
			return &ValidationError{Name: "fullname", err: fmt.Errorf(`ent: validator failed for field "User_Profile.fullname": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := user_profile.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "User_Profile.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := user_profile.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User_Profile.email": %w`, err)}
		}
	}
	return nil
}

func (_u *UserProfileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user_profile.Table, user_profile.Columns, sqlgraph.NewFieldSpec(user_profile.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccountNumber(); ok {
		_spec.SetField(user_profile.FieldAccountNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.Fullname(); ok {
		_spec.SetField(user_profile.FieldFullname, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(user_profile.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user_profile.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(user_profile.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user_profile.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user_profile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserProfileUpdateOne is the builder for updating a single User_Profile entity.
type UserProfileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserProfileMutation
}

// SetAccountNumber sets the "account_number" field.
func (_u *UserProfileUpdateOne) SetAccountNumber(v string) *UserProfileUpdateOne {
	_u.mutation.SetAccountNumber(v)
	return _u
}

// SetNillableAccountNumber sets the "account_number" field if the given value is not nil.
func (_u *UserProfileUpdateOne) SetNillableAccountNumber(v *string) *UserProfileUpdateOne {
	if v != nil {
		_u.SetAccountNumber(*v)
	}
	return _u
}

// SetFullname sets the "fullname" field.
func (_u *UserProfileUpdateOne) SetFullname(v string) *UserProfileUpdateOne {
	_u.mutation.SetFullname(v)
	return _u
}

// SetNillableFullname sets the "fullname" field if the given value is not nil.
func (_u *UserProfileUpdateOne) SetNillableFullname(v *string) *UserProfileUpdateOne {
	if v != nil {
		_u.SetFullname(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserProfileUpdateOne) SetStatus(v string) *UserProfileUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserProfileUpdateOne) SetNillableStatus(v *string) *UserProfileUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserProfileUpdateOne) SetEmail(v string) *UserProfileUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserProfileUpdateOne) SetNillableEmail(v *string) *UserProfileUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UserProfileUpdateOne) SetCreatedAt(v time.Time) *UserProfileUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UserProfileUpdateOne) SetNillableCreatedAt(v *time.Time) *UserProfileUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserProfileUpdateOne) SetUpdatedAt(v time.Time) *UserProfileUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UserProfileMutation object of the builder.
func (_u *UserProfileUpdateOne) Mutation() *UserProfileMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserProfileUpdate builder.
func (_u *UserProfileUpdateOne) Where(ps ...predicate.User_Profile) *UserProfileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserProfileUpdateOne) Select(field string, fields ...string) *UserProfileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User_Profile entity.
func (_u *UserProfileUpdateOne) Save(ctx context.Context) (*User_Profile, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserProfileUpdateOne) SaveX(ctx context.Context) *User_Profile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserProfileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserProfileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserProfileUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user_profile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserProfileUpdateOne) check() error {
	if v, ok := _u.mutation.AccountNumber(); ok {
		if err := user_profile.AccountNumberValidator(v); err != nil {
			return &ValidationError{Name: "account_number", err: fmt.Errorf(`ent: validator failed for field "User_Profile.account_number": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Fullname(); ok {
		if err := user_profile.FullnameValidator(v); err != nil {
			return &ValidationError{Name: "fullname", err: fmt.Errorf(`ent: validator failed for field "User_Profile.fullname": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := user_profile.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "User_Profile.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := user_profile.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User_Profile.email": %w`, err)}
		}
	}
	return nil
}

func (_u *UserProfileUpdateOne) sqlSave(ctx context.Context) (_node *User_Profile, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user_profile.Table, user_profile.Columns, sqlgraph.NewFieldSpec(user_profile.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User_Profile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user_profile.FieldID)
		for _, f := range fields {
			if !user_profile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user_profile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccountNumber(); ok {
		_spec.SetField(user_profile.FieldAccountNumber, field.TypeString, value)
	}
	if value, ok := _u.mutation.Fullname(); ok {
		_spec.SetField(user_profile.FieldFullname, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(user_profile.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user_profile.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(user_profile.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user_profile.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &User_Profile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user_profile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
